name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod download

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v1"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.USERNAME_DOCKER }}/${{ github.repository }}:${{ github.ref_name }} .
          echo $TOKEN_DOCKER | docker login -u $USERNAME_DOCKER --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ github.ref_name }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.USERNAME_DOCKER  }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
